### ISSUE TITLE
Multiple compilation errors on import

### ISSUE THREAD

**Issue by SamuelAB** [nvrmind/AnimVRUnityToolkit#1]
Hello,

I'm trying to import the AnimVR unity SDK along with some other asset packages, and am encountering multiple compilation issues. More specifically:

`Assertion failed: Assertion failed on expression: 'm_CurrentEntriesPtr != NULL && m_IsGettingEntries'
0x00000001412F15D6 (Unity) StackWalker::GetCurrentCallstack
0x00000001412F214F (Unity) StackWalker::ShowCallstack
0x00000001411B11C0 (Unity) GetStacktrace
0x00000001406DA453 (Unity) DebugStringToFile
0x00000001406DAC31 (Unity) DebugStringToFile
0x000000014110E194 (Unity) EditorMonoConsole::GetEntryInternal
0x0000000141362C50 (Unity) LogEntries_CUSTOM_GetEntryInternal
0x0000000045C4BD4D (Mono JIT Code) (wrapper managed-to-native) UnityEditor.LogEntries:GetEntryInternal (int,UnityEditor.LogEntry)
0x0000000045C3F16F (Mono JIT Code) [ConsoleWindow.cs:676] UnityEditor.ConsoleWindow:OnGUI () 
0x00000000029D7672 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FF8E0B664AF ((<unknown>)) 
0x00007FF8E0AB8A19 ((<unknown>)) 
0x00007FF8E0ABEF27 ((<unknown>)) 
0x00007FF8E0A7D34F ((<unknown>)) 
0x00000000029A0AB7 (Mono JIT Code) (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
0x000000000299EC12 (Mono JIT Code) [MonoMethod.cs:222] System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) 
0x0000000002A5465F (Mono JIT Code) [MethodBase.cs:115] System.Reflection.MethodBase:Invoke (object,object[]) 
0x0000000020F6EED5 (Mono JIT Code) [HostView.cs:295] UnityEditor.HostView:Invoke (string,object) 
0x0000000020F6ED7A (Mono JIT Code) [HostView.cs:288] UnityEditor.HostView:Invoke (string) 
0x00000000425D5C0E (Mono JIT Code) [HostView.cs:255] UnityEditor.HostView:InvokeOnGUI (UnityEngine.Rect) 
0x00000000425C62D3 (Mono JIT Code) [DockArea.cs:387] UnityEditor.DockArea:OldOnGUI () 
0x00000000425B1298 (Mono JIT Code) [IMGUIContainer.cs:179] UnityEngine.Experimental.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event) 
0x00000000425B04C8 (Mono JIT Code) [IMGUIContainer.cs:333] UnityEngine.Experimental.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event) 
0x0000000020F61DC8 (Mono JIT Code) [IMGUIContainer.cs:317] UnityEngine.Experimental.UIElements.IMGUIContainer:HandleEvent (UnityEngine.Experimental.UIElements.EventBase) 
0x0000000020F5A09F (Mono JIT Code) [EventDispatcher.cs:459] UnityEngine.Experimental.UIElements.EventDispatcher:PropagateEvent (UnityEngine.Experimental.UIElements.EventBase) 
0x0000000020F57B2A (Mono JIT Code) [EventDispatcher.cs:340] UnityEngine.Experimental.UIElements.EventDispatcher:DispatchEvent (UnityEngine.Experimental.UIElements.EventBase,UnityEngine.Experimental.UIElements.IPanel) 
0x000000004258354F (Mono JIT Code) [UIElementsUtility.cs:251] UnityEngine.Experimental.UIElements.UIElementsUtility:DoDispatch (UnityEngine.Experimental.UIElements.BaseVisualElementPanel) 
0x000000004258301B (Mono JIT Code) [UIElementsUtility.cs:78] UnityEngine.Experimental.UIElements.UIElementsUtility:ProcessEvent (int,intptr) 
0x0000000042582B3D (Mono JIT Code) [GUIUtility.cs:175] UnityEngine.GUIUtility:ProcessEvent (int,intptr) 
0x0000000042582CFE (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_bool_int_intptr (object,intptr,intptr,intptr)
0x00007FF8E0B664AF ((<unknown>)) 
0x00007FF8E0AB8A19 ((<unknown>)) 
0x0000000140A2EAEC (Unity) scripting_method_invoke
0x0000000140A2243A (Unity) ScriptingInvocation::Invoke
0x0000000140A234EA (Unity) ScriptingInvocation::Invoke<bool>
0x000000014028278E (Unity) IMGUIScriptingClasses::ProcessEvent
0x000000014112A2AF (Unity) GUIView::ProcessRetainedMode
0x00000001413F9748 (Unity) GUIView::OnInputEvent
0x000000014112A193 (Unity) GUIView::ProcessInputEvent
0x00000001413F1715 (Unity) GUIView::ProcessEventMessages
0x00000001413FB70A (Unity) GUIView::GUIViewWndProc
0x00007FF93247B85D (USER32) CallWindowProcW
0x00007FF93247B1EF (USER32) DispatchMessageW
0x000000014140EAB0 (Unity) MainMessageLoop
0x00000001414103B5 (Unity) WinMain
0x0000000141E643A8 (Unity) __tmainCRTStartup
0x00007FF932C61FE4 (KERNEL32) BaseThreadInitThunk
0x00007FF932D9EFC1 (ntdll) RtlUserThreadStart`

`ArgumentException: Value does not fall within the expected range.
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.LanguageOf (SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit unit)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.CompilationUnits (System.String method)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.CompilationUnits ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder..ctor ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder.CreateSolutionFromAssetDatabase ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilesGenerator.GenerateProject ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilePostprocessor.OnPreGeneratingCSProjectFiles ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.OnPreGeneratingCSProjectFiles () (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:61)
UnityEditor.VisualStudioIntegration.SolutionSynchronizer.Sync () (at C:/buildslave/unity/build/Editor/Mono/VisualStudioIntegration/SolutionSynchronizer.cs:189)
UnityEditor.VisualStudioIntegration.SolutionSynchronizer.SyncIfNeeded (IEnumerable`1 affectedFiles) (at C:/buildslave/unity/build/Editor/Mono/VisualStudioIntegration/SolutionSynchronizer.cs:178)
UnityEditor.SyncVS.PostprocessSyncProject (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at C:/buildslave/unity/build/Editor/Mono/SyncProject.cs:177)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:31)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

`Assets/MetaSDK/Meta/Reconstruction/Scripts/MetaReconstruction.cs(512,21): error CS1593: Delegate `System.Threading.ParameterizedThreadStart' does not take `0' arguments
`

`Assets/MetaSDK/Meta/Reconstruction/Scripts/MetaReconstruction.cs(532,62): error CS1061: Type `MeshData' does not contain a definition for `Name' and no extension method `Name' of type `MeshData' could be found. Are you missing an assembly reference?
`

There are two additional errors concerning missing definitions for "Vertices" and "Triangles" within the MeshData type.

The other asset packages included in the project are the MetaSDK by metavision as well as TiltBrush.

Any guidance would be appreciated here. 

Thanks,

**Comment by daseyb** [comment]
Sorry for the late reply!

I haven't seen those errors before. What version of Unity are you using?

**Comment by SamuelAB** [comment]
We're using Unity 2017.0f3.

Apologies for posting just the raw dump here. Some of these were caused specifically by the MetaSDK. 


The MeshData errors seem to be caused by both the AnimVR and the MetaSDK packages declaring a MeshData class and not always instantiating the namespaced version. 

We've worked around the issue by renaming the MeshData class in the AnimVR package to animVRMeshData as well as any instantiations. Since this required changing your package directly, it doesn't seem like the proper solution though.

We'll be opening a ticket on Meta's side with the same feedback. 

Thanks!

**Comment by SamuelAB** [comment]
@daseyb  Any update on this? We'd love to continue making VR animations.

**Comment by daseyb** [comment]
Regarding the error: I don't think it's coming from the Unity toolkit, looks like something is going wrong with the Unity <-> Visual Studio integration.

We are aware of the namespace issues, unfortunately it's not something we can fix right now. Renaming the classes will result in errors when you try to load a stage with an imported mesh.

If that's not a feature you are using though, renaming them on your end is probably the best solution until we can fix it properly.
