### ISSUE TITLE
How to slim down Build?

### ISSUE THREAD

**Issue by momo-the-monster** [nvrmind/AnimVRUnityToolkit#2]
We've got a project with many minutes of AnimVR sequences imported, and when we go to build the project, we get errors because the one scene containing all of the animations is too large (serializes to 5+GB, Unity caps a single serializable file at 4GB). Do you have a recommended way to split animations into AssetBundles or some other way to load in such large files if they're all on the same timeline?

**Comment by daseyb** [comment]
I have to admit, in my 6 years as a Unity developer I never ran into that
particular limitation.

I would probably try to split the sequence into multiple scenes and load
the next one asynchronously while the previous one is playing.
Of course, that's inconvenient when everything should be on the same
timeline.

**Comment by momo-the-monster** [comment]
Thanks, @daseyb! We split the assets into AssetBundles and loaded them all at app start, so it freezes for 3 minutes at first but then it all plays swimmingly. Worked perfect for our use case, which was [a live performance](https://www.youtube.com/watch?v=V9ZTbLvn6vg).
