### ISSUE TITLE
Unity 2018.2.0f2 bug + fix

### ISSUE THREAD

**Issue by staus** [nvrmind/AnimVRUnityToolkit#3]
Just upgraded our project to Unity 2018.2.0f2 and get an error that PlayableBinding is handled different.

In **AnimVRFramesAsset.cs** and **AnimControlPlayableAsset.cs** I changed the binding like so:

```javascript
var binding = ScriptPlayableBinding.Create(this.name + " Parent", this, typeof(GameObject));
// var binding = new PlayableBinding();
// binding.streamType = DataStreamType.None;
// binding.sourceObject = this;
// binding.streamName = this.name + " Parent";
// binding.sourceBindingType = typeof(GameObject);
return new PlayableBinding[] { binding };
```

(In **AnimControlPlayableAsset.cs** "Parent" should be "Source" of course)

**Comment by daseyb** [comment]
Ah, Unity 2018.2 just released, right?
I'll update the toolkit soonish and leave the issue open so people who run
into it until then know what to do :)

**Comment by staus** [comment]
Yeah today I think :) Not quite sure how PlayableBinding works, so don't hold me up on my solution without checking, haha

**Comment by daseyb** [comment]
Fix is in the repository now :)
