### ISSUE TITLE
Toolkit compatibility / Stage import error

### ISSUE THREAD

**Issue by philmaas** [nvrmind/AnimVRUnityToolkit#4]
Hey guys,
congrats for releasing AnimVR also on Oculus!
What is your roadmap regarding the toolkit, which unity versions will be supported and how do you plan to update it with every new animVR or unity version?

right now it doesn't import stages in 2017.3 or 2018 with the latest animvr from the oculus store.

`NullReferenceException: Object reference not set to an instance of an object
AnimData.LoadFromFile (System.String filepath) (at Assets/AnimVR UnityImporter/Utils/AnimData.cs:3509)
ANIMVR.AnimVRImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Assets/AnimVR UnityImporter/Editor/AnimVRImporter.cs:82)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (ImportRequest request) (at C:/buildslave/unity/build/Editor/Mono/AssetPipeline/ScriptedImporter.cs:123)`

**Comment by daseyb** [comment]
Oops, I forgot to update the GitHub repo. If it's urgent you can download the latest toolkit here: https://download.nvrmind.io/bob/toolkits/download/AnimVR_10_00_16

I'll update the repository asap too :)

**Comment by daseyb** [comment]
Ok, Github is updated :)

**Comment by philmaas** [comment]
awesome thanks :))
